import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Container } from '@mui/material';
import bg from '../public/home-bg.jpg';

export default function Home() {
  return (
    <div>
      <Head>
        <title>COOLNAME SHOP</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href='icons8.png' />
      </Head>

      <main className={styles.main}>
        <Container className='image-container'>
          <Image src={bg} layout='fill' quality={75} placeholder='blur' objectFit='cover' objectPosition={'center'} priority></Image>
        </Container>
      </main>

    </div>
  )
}
